### ISSUE TITLE
pam-1.1.1-17.el6.src.rpm is left in / in sequenceiq/pam:latest

### ISSUE THREAD

**Issue by dajobe** [sequenceiq/docker-pam#2]
The docker build for sequenceiq/pam:latest leaves around a source RPM in / you might want to cleanup next time you build it:

    $ docker run -t -i --rm sequenceiq/pam /bin/bash
    bash-4.1# ls -l /*rpm
    -rw-r--r-- 1 root root 1288261 Nov 25  2013 /pam-1.1.1-17.el6.src.rpm
    bash-4.1#

I notice this because it's the base of many of your other docker images.

**Comment by akanto** [comment]
Thanks. The image is cleaned up. The *.rpm from / and the ~/rpmbuild has been removed.
